### ISSUE TITLE
full of virUs!!1!!!

### ISSUE THREAD

**Issue by Makiah** [FRCDiscord/ModmailBot#1]
d0N'T download!!!!there r BIG viruses on my compoter now,even this grosss one called pithon.  ZERO stars!!!!

**Comment by TomOrth** [comment]
Closing since this is just a troll post. Next time you post an issue, please make sure its a legitimate concern and to act semi-professional.

**Comment by Makiah** [comment]
Sorry about that, @guineawheek did something similar to this on one of my repositories and I thought this would be a way to repay the favor, so to speak :P.  No ill intentions, sorry if it came across that way.

**Comment by TomOrth** [comment]
Ah okay. Gotcha.

**Comment by guineawheek** [comment]
@Makiah _please check to see if it's actually my repository before shitposting in it next time_

**Comment by Makiah** [comment]
@guineawheek no
